Fix/challenge
Team-O2/Front-end pull request #61
Opened 2021-07-30 07:41 UTC by Hyoin-Kim

### ✅ PR check list
```
- Challenge- 파일명 변경
- style.ts 파일 분리
- 코드 디렉토리 정리 및 코드 컨벤션 통일
```

### 관련 이슈

<!— 관련있는 이슈 번호(#000)을 적어주세요. —>

### 변경 사항 및 이유

<!— 변경한 내용과 그 이유를 적어주세요. —>

### PR Point

<!— 리뷰어 분들이 집중적으로 보셨으면 하는 내용을 적어주세요 —>

### 참고 사항

<!— 참고할 사항이 있다면 적어주세요. —>

2021-07-30 08:36 UTC, su-bin99 commented on README.md
> + ┃ ┃ ┣ 📂ChallengeDetailCard
오 리드미까지 바꾸는 디테일

2021-07-30 08:36 UTC, su-bin99 commented on src/components/molecules/ChallengeDetailCard/index.tsx
>  import DeleteModal from '../DeleteModal';
얘네도 한번에 불러오는거로 정리하면 좋을듯!!

2021-07-30 08:36 UTC, su-bin99 commented on src/components/molecules/ChallengeEditCard/index.tsx
>  import Modal from '../../atoms/Modal/index';
이것도 한번에 불러오면 좋을거가타!

2021-07-30 08:36 UTC, su-bin99 commented on src/components/molecules/ChallengeEditCard/index.tsx
> +            onChange={totalOnChange}
나 이거 함수를 handleTotalChange 이런식으로 했거든? 함수라 동사로 해야한다고 해가지고 ,, 이렇게 해도 되려나?

2021-07-30 08:44 UTC, rdd9223 requested changes
한번 확인해주세요!

2021-07-30 08:44 UTC, rdd9223 commented on src/assets/images/index.ts
> +export { default as CharacterColor3 } from './character_color3_Img.svg';
우리 아이콘 붙이기로 하지 않았나요!

2021-07-30 08:44 UTC, rdd9223 commented on src/components/molecules/ChallengeComment/index.tsx
>  import ChallengeSingleComment from 'components/molecules/ChallengeSingleWrite';
이것들도 같이 molecules로 묶으면 보기 좋겠네요!

2021-07-30 08:44 UTC, rdd9223 commented on src/components/molecules/ChallengeComment/index.tsx
> +import SCommentList from './style';
스타일 컴포넌트는 S안붙어도 될거같은 느낌...?

2021-07-30 08:44 UTC, rdd9223 commented on src/components/molecules/ChallengeEditCard/index.tsx
> +} from 'assets/images/index';
```suggestion
} from 'assets/images';
```
이렇게 하는게 어떡까요?

2021-07-30 08:44 UTC, rdd9223 commented on src/components/molecules/ChallengeEditCard/index.tsx
>  import Modal from '../../atoms/Modal/index';
```suggestion
import Button from '../../atoms/Button';
import Modal from '../../atoms/Modal/index';
```
이부분도 components/atoms로 묶으면 깔끔하겠네요

2021-07-30 08:44 UTC, rdd9223 commented on src/components/molecules/ChallengeEditCard/index.tsx
> +  const totalOnChange = (e: any) => {
any...

2021-07-30 08:44 UTC, rdd9223 commented on src/components/molecules/RegisterHeader/style.ts
> +const SHeader = Styled.div<ISHeader>`
```suggestion
export const SHeader = Styled.div<ISHeader>`
```
나중엔 이렇게 선언하는게 더 나을거에요!

2021-07-30 08:45 UTC, rdd9223 commented on src/components/molecules/ChallengeEditCard/index.tsx
> +            onChange={totalOnChange}
수빈이 말이 맞는듯!!

2021-07-30 08:49 UTC, shji023 reviewed
코드 수정 꼼꼼하게 잘했네용 임포트부분 겹치는거  index에서 불러오는걸로 바꾸면 좋겠다!! 수고하셨슴당~~

2021-07-30 08:49 UTC, shji023 commented on README.md
> + ┃ ┃ ┣ 📂ChallengeDetailCard
> 오 그러네 ㅋㅋㅋㅋ

2021-07-30 08:49 UTC, shji023 commented on src/assets/images/index.ts
> +export { default as LoginAlertIcon, default as LoginModal } from './loginAlert.svg';
이거 나도 나중에 LoginAlertIcon으로 바꿀게 !

2021-07-30 08:49 UTC, shji023 commented on src/components/molecules/ChallengeComment/index.tsx
>  import ChallengeSingleComment from 'components/molecules/ChallengeSingleWrite';
모듈화 묶으면 좋을듯~!

2021-07-30 08:49 UTC, shji023 commented on src/components/molecules/ChallengeSingleWrite/index.tsx
> +import ChallengeReCommentList from '../ReplyComment';
여기도 똑같은거끼리 임포트 묶으면 좋을듯!@

2021-07-30 15:45 UTC, Hyoin-Kim commented on src/components/molecules/ChallengeComment/index.tsx
> +import SCommentList from './style';
꼭 참고해서 2차 스프린트 때까지 수정하겠습니다!

2021-07-30 15:46 UTC, Hyoin-Kim commented on src/components/molecules/RegisterHeader/style.ts
> +const SHeader = Styled.div<ISHeader>`
넵 스타일부분은 전체적으로 건들여야해서 한번에 고쳐서 올리겠습니다~

2021-07-30 16:40 UTC, rdd9223 requested changes
한번 더 확인바람!

2021-07-30 16:40 UTC, rdd9223 commented on src/components/molecules/ChallengeEditCard/index.tsx
> +  const handleTotalOnChange = (e: any) => {
any 멈춰...

2021-07-30 16:40 UTC, rdd9223 commented on src/components/molecules/ChallengeSingleWrite/index.tsx
> +import { ICommentData } from 'components/molecules/ChallengeDetailCard';
요거도 합치면 좋을듯!

2021-07-31 01:44 UTC, shji023 reviewed
확인완료!

2021-07-31 01:44 UTC, shji023 commented on src/components/molecules/ChallengeEditCard/index.tsx
> +  const handleTotalOnChange = (e: any) => {
나도any몇개 있는데 오류고칠때 꼭 바꿀게!

2021-07-31 04:32 UTC, merged